### PR TITLE
'java.lang.NullPointerException: Required parameter project must be s…

### PR DESCRIPTION
**Pull request by sharkannon**
…pecified.' when trying to create a google blobstore, based on https://stackoverflow.com/questions/46308973/project-parameter-not-found-when-creating-google-cloud-bucket-java-api it appears that projectid needs to be set independant of credentials.

(brief, plain english overview of your changes here)

This pull request makes the following changes:
* (your change here)
* (another change here)
* (etc)

(If there are changes to the UI, please include a screenshot so we
know what to look for!)

(If there are changes to user behavior in general, please make sure to
update the docs, as well)

It relates to the following issue #s:
* Fixes #X

### CODE REVIEW

**Comment by sharkannon** [comment]
this is for work.. we have multiple projects, wondering if that's the problem.

As for moving it up, if you want to, go for it... TBH I'm not really a java dev and this was pushing my java knowledge :)

**Comment by nblair** [comment]
I think you're right, multiple projects may be the cause.

Integration tests look to pass locally. Have you confirmed this works in a Nexus Repository Manager 3.13 install?

**Comment by sharkannon** [comment]
No, I'd already upgraded my system to 3.14 so couldn't backport.

**Comment by sharkannon** [comment]
downgrade I mean

**Comment by nblair** [comment]
Ok - I'll give it a quick run later tonight, and likely merge both this and #16. Thank you!

**Comment by sharkannon** [comment]
actually, I'm an idiot.. I can move that up to the parent class no problem.. Java scares me sometimes, I am used to python :)

**Pull request merged**
